[package]
name = "libkrun-sys"
version = "0.1.0"
edition = "2021"
authors = ["A3S Lab Team"]
description = "FFI bindings to libkrun"
license = "MIT"

links = "krun"

[build-dependencies]
pkg-config = "0.3"
num_cpus = "1.16"

[dependencies]
libc = "0.2"

[features]
default = []
