apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: a3s-box-system

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - daemonset.yaml
  - runtime-class.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/a3s-lab/a3s-box-cri
    newTag: latest
